language: android
sudo: required
dist: trusty

jdk:
  - oraclejdk8

env:
  global:
    - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - extra-android-m2repository
    - android-26
    - extra-google-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license-.+'
    - '.+'

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - sdkmanager tools
  - sdkmanager "system-images;android-21;default;armeabi-v7a"
  - pip install --user codecov

before_script:
  - echo no | avdmanager create avd --force -n test -k "system-images;android-21;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew jacocoTestReportDebug
  - ./gradlew connectedCheck

after_success:
  - codecov

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

